version: "3"
services:
  nodeassignment1:
    container_name: nodeassignment1
    restart: always
    build: .
    ports:
      - "8080:3010"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27018:27017"